project:
  type: website
  output-dir: docs
website:
  title: "Liam Boyd"
  navbar:
    left:
      - href: about.qmd
        text: About Me
      - projects.qmd

format:
  html:
    theme:
      light: brite
      dark: brite
    css: styles.css
    toc: true
    page-layout: full

editor: visual