project:
  type: website
  resources:
    - "posts/movie_analysis.html"
  output-dir: docs
website:
  title: "Liam Boyd"
  navbar:
    left:
      - href: about.qmd
        text: About Me
      - projects.qmd

format:
  html:
    theme:
      light: lux
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual